services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      app_network:
        ipv4_address: 172.10.0.30

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.0-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - 9000:9000
    volumes:
      - ./volumes/wordpress:/var/www/html
    networks:
      app_network:
        ipv4_address: 172.10.0.20


  webserver:
    depends_on:
      - wordpress
    image: nginx:1.25.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./custom_nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_network:
        ipv4_address: 172.10.0.10


networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
